VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "FakeTextWriter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
Implements ITextWriter

Private Sub ITextWriter_WriteLine(ParamArray TextAndArgs() As Variant)

End Sub

Private Sub ITextWriter_WriteText(ByVal Text As String, ParamArray Args() As Variant)

End Sub
